# Generated by Django 4.1.2 on 2022-10-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_network_asset_networks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.CharField(db_index=True, max_length=40)),
                ('balance', models.DecimalField(decimal_places=20, max_digits=50, verbose_name='base balance')),
                ('watch', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assets', models.ManyToManyField(to='core.asset', verbose_name='account assets')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.network', verbose_name='network')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
