# Generated by Django 4.1.2 on 2022-10-31 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
