# Generated by Django 4.1.2 on 2022-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_assets_remove_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(db_index=True, max_length=42),
        ),
    ]
