# Generated by Django 4.1.2 on 2022-10-31 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_network_asset_networks'),
        ('account', '0004_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.network'),
        ),
    ]
