# Generated by Django 4.1.2 on 2022-10-31 07:58

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_created_at_alter_account_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=20, max_digits=50)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='5 minute')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
