# Generated by Django 4.1.2 on 2022-10-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='AccountBalance',
        ),
    ]
