# Generated by Django 4.1.2 on 2022-10-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_table_alter_accountbalance_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='accountbalance',
            table='account_balance',
        ),
    ]
