# Generated by Django 4.1.2 on 2022-10-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_table_alter_accountbalance_table'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='accountbalance',
            order_with_respect_to='account',
        ),
    ]
