# Generated by Django 4.1.2 on 2022-10-29 21:13

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('numerator', models.CharField(max_length=20)),
                ('denominator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 minute')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tradingpair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('network', models.ManyToManyField(to='api.network', verbose_name='supported networks')),
            ],
        ),
    ]
