# Generated by Django 4.1.2 on 2022-10-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='denominator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominator', to='api.asset'),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='numerator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerator', to='api.asset'),
        ),
    ]
