# Generated by Django 4.1.2 on 2022-10-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tradingpair_denominator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
