# Generated by Django 4.1.2 on 2022-10-29 22:10

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('denominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominator', to='core.asset')),
                ('numerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerator', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 minute')),
                ('price', models.DecimalField(decimal_places=20, max_digits=50)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tradingpair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='network',
            field=models.ManyToManyField(to='core.network', verbose_name='supported networks'),
        ),
    ]
