# Generated by Django 4.1.2 on 2022-10-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='network',
            new_name='networks',
        ),
    ]
