# Generated by Django 4.1.2 on 2022-11-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_accountbalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'managed': False},
        ),
    ]
