# Generated by Django 4.1.2 on 2022-11-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_account_options_alter_accountbalance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountbalance',
            options={},
        ),
    ]
